const data = {
  products: [
    {
      name: 'Arduino UNO',
      slug: 'Arduino UNO',
      category: 'Microcontrollers',
      image: '/images/3.png', // 679px × 829px
      price: 100,
      countInStock: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Raspberry Pi',
      slug: 'Raspberry Pi',
      category: 'Microcontrollers',
      image: '/images/3.png',
      price: 150,
      countInStock: 20,
      // brand: 'Adidas',
      // rating: 4.0,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Servo Motor',
      slug: 'Servo Motor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 25,
      countInStock: 15,
      // brand: 'Nike',
      // rating: 4.5,
      // numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'LCD Screen',
      slug: 'LCD Screen',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Ultrasonic Sensor',
      slug: 'Ultrasonic Sensorn',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'PIR Sensor',
      slug: 'PIR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'IR Sensor',
      slug: 'IR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Membrane Keypad',
      slug: 'Membrane Keypad',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: '7 Segment Display',
      slug: '7 Segment Display',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'RFID Module',
      slug: 'Sensor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
