import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'ElectroCity',
      email: 'ElectroCity@gmail.com',
      password: bcrypt.hashSync('Electrocity'),
      isAdmin: true,
    },
    {
      name: 'Kim',
      email: 'Kim@gmail.com',
      password: bcrypt.hashSync('Kim'),
      isAdmin: true,
    },
    {
      name: 'Crisabel',
      email: 'Crisabel@gmail.com',
      password: bcrypt.hashSync('Crisabel'),
      isAdmin: true,
    },
    {
      name: 'EllaG',
      email: 'EllaG@gmail.com',
      password: bcrypt.hashSync('EllaG'),
      isAdmin: true,
    },
    {
      name: 'User',
      email: 'User@gmail.com',
      password: bcrypt.hashSync('User'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Arduino UNO',
      slug: 'Arduino UNO',
      category: 'Microcontrollers',
      image: '/images/3.png', // 679px × 829px
      price: 100,
      countInStock: 10,
      description: 'high quality shirt',
    },
    {
      //_id: '2',
      name: 'Raspberry Pi',
      slug: 'Raspberry Pi',
      category: 'Microcontrollers',
      image: '/images/3.png',
      price: 150,
      countInStock: 0,
      // brand: 'Adidas',
      // rating: 4.0,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '3',
      name: 'Servo Motor',
      slug: 'Servo Motor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 25,
      countInStock: 15,
      // brand: 'Nike',
      // rating: 4.5,
      // numReviews: 14,
      description: 'high quality product',
    },
    {
      //_id: '4',
      name: 'LCD Screen',
      slug: 'LCD Screen',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '5',
      name: 'Ultrasonic Sensor',
      slug: 'Ultrasonic Sensorn',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '6',
      name: 'PIR Sensor',
      slug: 'PIR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '7',
      name: 'IR Sensor',
      slug: 'IR Sensor',
      category: 'Sensor',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '8',
      name: 'Membrane Keypad',
      slug: 'Membrane Keypad',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      //_id: '9',
      name: '7 Segment Display',
      slug: '7 Segment Display',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '10',
      name: 'RFID Module',
      slug: 'Sensor',
      category: 'Input/Output',
      image: '/images/3.png',
      price: 65,
      countInStock: 5,
      // brand: 'Puma',
      // rating: 4.5,
      // numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
